# Generated by Django 3.2 on 2022-06-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220604_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(choices=[('2', 2), ('3', 3), ('4', 4), ('5', 5), ('6', 6)]),
        ),
    ]
